name: careconnect CI/CD Pipeline

on:
   pull_request:
      branches: [develop]

jobs:
   Setup_Integration:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Build docker image
           run: docker build . --tag careconnect-backend:$(date +%s)

         - name: Setup Nodejs server
           uses: actions/setup-node@v2
           with:
              node-version: '20'

         - name: Install dependencies
           run: |
              npm install
              echo "Install node packages completed"

         - name: Run Linter
           run: |
            npm run lint
            echo "No linting error reported"

         - name: Run Unit Test
           run: | 
              npm run test:unit
              echo "Unit test completed"

         - name: Run End-to-End Test
           run: |
            npm run test:e2e
            echo "End-to-End tests completed"
      
         - name: Build Application
           run: |
            npm run build           
            echo "Build step completed"

   deploy:
    runs-on: ubuntu-latest
    needs: Setup_Integration  # Ensure deployment only happens after build
    #Skip if no AWS credentials if: ${{ secrets.AWS_ACCESS_KEY_ID }}  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Mock Deployment (Skip real deployment)
      run: |
        echo "Skipping deployment as AWS server is not available"
        echo "Mocking deployment process..."