name: careconnect CI/CD Pipeline

on:
   pull_request:
      branches: [develop]

jobs:
   setup:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Build docker image
           run: docker build . --tag careconnect-backend:$(date +%s)

         - name: Setup Nodejs server
           uses: actions/setup-node@v2
           with:
              node-version: '20'

         - name: Install dependencies
           run: npm install

   lint:
       runs-on: ubuntu-latest
       needs: setup

       steps:
           - name: Run Linter
             run: npm run lint
 
   test:
      runs-on: ubuntu-latest
      needs: lint

      steps:
      - name: Run Unit Test
        run: npm run test:unit

      - name: Run End-to-End Test
        run: npm run test:e2e"

   build:
      runs-on: ubuntu-latest
      needs: test
      steps:
      
      - name: Build Application
        run: npm run build           

   deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment only happens after build
    if: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}  # Skip if no AWS credentials

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Mock Deployment (Skip real deployment)
      run: |
        echo "Skipping deployment as AWS server is not available"
        echo "Mocking deployment process..."